apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-lackky
  name: php-lackky
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: php-lackky
